#!/bin/sh

checktmpfs=$(cat /etc/fstab|grep '/tmp'|grep 'tmpfs')

if [ "${checktmpfs}" != "" ] ; then
    echo "This server have '/tmp' with 'tmpfs' detect."
	echo "Modified '/etc/fstab' where remove 'tmpfs' in '/tmp' line and then reboot."
	echo "Without remove, backup/restore may have a trouble."
	exit
fi

T="$(date +%s%N)"

if rpm -qa|grep mysql55 >/dev/null 2>&1 ; then
	echo "Already use mysql55. No replace"
else
	if rpm -qa|grep mysql >/dev/null 2>&1 ; then
		yum clean all >/dev/null 2>&1
		echo "Replace mysql to mysql55"
		yum replace mysql --replace-with=mysql55 -y >/dev/null 2>&1
		yum install php52s -y >/dev/null 2>&1
		yum update php52s -y >/dev/null 2>&1
	fi
fi

if $(ls -al /usr/bin/lxphp.exe|grep /usr/local/lxlabs >/dev/null 2>&1) ; then
	yum remove lxphp lxlighttpd lxzend >/dev/null 2>&1
	
	rm -rf /usr/local/lxlabs/ext >/dev/null 2>&1
	
	rm -rf /usr/bin/lxphp.exe
	
	yum install php52s hiawatha -y >/dev/null 2>&1
fi

. /script/directory
lxphp.exe ../bin/common/cleanup.php

echo
echo "*** Restart services - BEGIN ***"
sh /script/restart-services
echo "*** Restart services - END ***"
echo

# Time interval in nanoseconds
T="$(($(date +%s%N)-T))"
# Seconds
S="$((T/1000000000))"
# Milliseconds
M="$((T/1000000))"

printf "Process Time: %02d:%02d:%02d:%02d.%03d (dd:hh:mm:ss:xxxxxx)\n" \
	"$((S/86400))" "$((S/3600%24))" "$((S/60%60))" "$((S%60))" "${M}"


